# Generated by Django 4.1.7 on 2023-03-26 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_Name',
            field=models.CharField(default='Not defined', max_length=20),
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=20)),
                ('no_emp', models.FloatField(default=0)),
                ('total_sales', models.FloatField(default=0)),
                ('pending_order', models.FloatField(default=0)),
                ('confirmed_order', models.FloatField(default=0)),
                ('no_product', models.FloatField(default=0)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('images', models.ImageField(null=True, upload_to='comment')),
                ('rating', models.FloatField(null=True)),
                ('like', models.FloatField(null=True)),
                ('dislike', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
    ]
