# Generated by Django 4.1.7 on 2023-03-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_company_owner_name_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coupon'),
        ),
    ]
