# Generated by Django 4.1.7 on 2023-03-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_company_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.comments'),
        ),
    ]
