# Generated by Django 4.1.7 on 2023-04-01 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_company_orderitem_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
    ]
