# Generated by Django 4.1.7 on 2023-04-01 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_company_orderitem_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default='Tech Love V', on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='company',
            field=models.ForeignKey(default='Tech Love V', on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
    ]
