# Generated by Django 4.1.7 on 2023-04-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_subcategory_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='main',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
