# Generated by Django 4.1.7 on 2023-04-01 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_item_subcategory_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='comment'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.comments'),
        ),
    ]
