# Generated by Django 4.1.7 on 2023-04-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_comments_dislike_alter_comments_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='shop.subcategory'),
        ),
    ]
