# Generated by Django 4.1.7 on 2023-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='../static/img/image_not_available.png', upload_to='Porduct'),
        ),
    ]
