# Generated by Django 4.1.7 on 2023-04-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='shop.subcategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.company'),
        ),
    ]
