# Generated by Django 4.1.7 on 2023-04-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_order_company_alter_orderitem_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='company',
        ),
    ]
