# Generated by Django 4.1.7 on 2023-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_item_date_published_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
