# Generated by Django 4.1.7 on 2023-03-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_brand_name_company_comments_item_comments_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
    ]
